#!/bin/bash

## Parameters for sending email:
source /usr/local/bin/.email-params
SUBJECT="/etc backup from $HOSTNAME"
BODY="The attached archive contains a current backup of /etc from $HOSTNAME."
ATTACHMENT="/tmp/etc.tar.gz"

cd /etc

## Create the Archive:
sudo tar -zcvf /tmp/etc.tar.gz *

## Email the archive:
/bin/echo $BODY | /usr/bin/mailx -r $SMTPFROM -s "$SUBJECT" -a $ATTACHMENT -S smtp="$SMTPSERVER" -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user="$SMTPUSER" -S smtp-auth-password="$SMTPPASS" -S ssl-verify=ignore $SMTPTO

## Remove the file since we're done with it:
sudo rm /tmp/etc.tar.gz
