#!/bin/bash

## Import parameters for sending email:
source /usr/local/bin/.email-params
SUBJECT="$HOSTNAME weekly update"
BODY="Update results attached."
ATTACHMENT="/tmp/update.txt"

## Insert the message body:
echo "The results of this week's update are as follows:" > /tmp/update.txt
echo "----------" >> /tmp/update.txt

## Check if the local host is Debian-based:
if [ -d /etc/apt ]
then
	## Run the Debian version of the update commands:
	sudo apt-get update
	sudo apt-get dist-upgrade -y >> /tmp/update.txt
fi

## Check if the local host is Arch-based:
if [ -f /etc/pacman.conf ]
then
	## Run the Arch version of the update commands:
	sudo pacman -Syyy
	sudo pacman -Su --noconfirm >> /tmp/update.txt
fi

## Send the update notification:
/bin/echo $BODY | /usr/bin/mailx -r $SMTPFROM -s "$SUBJECT" -a $ATTACHMENT -S smtp="$SMTPSERVER" -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user="$SMTPUSER" -S smtp-auth-password="$SMTPPASS" -S ssl-verify=ignore $SMTPTO

## Remove the output file, since we're done with it:
sudo rm /tmp/update.txt
