# Current PS1:
tty -s && export PS1="[\u@\h:\W]\\$ \[$(tput sgr0)\]"

# Env
export TERM=xterm-256color
export EDITOR=vim

# Command aliases
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias l.='ls -lha --time-style=long-iso --color=auto'
alias ll='ls'
alias ls='ls -lh --time-style=long-iso --color=auto'
alias lsmount='mount |column -t'
alias c='clear'
alias diff='colordiff'
alias grep='grep --color=auto'
alias mkdir='mkdir -pv'
alias ports='netstat -tulanp'
alias h='history'
alias j='jobs -l'
alias svim='sudo vim'
alias wget='wget -c'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
 
## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

# Safetynets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'
 
# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
 
# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# reload bash config
alias reload="source ~/.bashrc"

if [ -d /etc/apt ]; then
    alias update='sudo apt-get update && sudo apt-get dist-upgrade'
    alias install='sudo apt-get install'
fi

if [ -f /etc/yum.conf ]; then
    alias update='sudo yum update'
    alias install='sudo yum install'
fi

## Functions

# Make a directory, then go there
md() {
    test -n "$1" || return
    mkdir -p "$1" && cd "$1"
}

# "path" shows current path, one element per line.
# If an argument is supplied, grep for it.
path() {
    test -n "$1" && {
        echo $PATH | perl -p -e "s/:/\n/g;" | grep -i "$1"
    } || {
        echo $PATH | perl -p -e "s/:/\n/g;"
    }
}
