#!/bin/bash

## Import parameters for sending email.
source /usr/local/bin/.email-params
MESSAGESUBJECT1="$HOSTNAME is shutting down due to a power issue"
MESSAGESUBJECT2="Power is back online!"

if [ -f /share/public/upsup ]
then
	## System is online, send message.
	rm /share/public/upsup
	sleep 2m
	sendEmail -f $SMTPFROM -t $SMTPTO -u $MESSAGESUBJECT2 -m "Main power is back online. Systems are back up!" -s $SMTPSERVER -xu $SMTPUSER -xp $SMTPPASS -o tls=no
fi

if [ -f /share/public/upsdown ]
then
	## UPS is down. Initiate halt.
	mv /share/public/upsdown /share/public/upsup
	sendEmail -f $SMTPFROM -t $SMTPTO -u $MESSAGESUBJECT1 -m "The UPS didn't come back online in time. Initiating precautionary system halt." -s $SMTPSERVER -xu $SMTPUSER -xp $SMTPPASS -o tls=no
	sleep 15
	sudo halt
fi
