#!/bin/bash

## Parameters for sending email:
source /usr/local/bin/.email-params
SUBJECT="Installed packages on $HOSTNAME"
BODY="List of installed packages attached."
ATTACHMENT="/tmp/installed_packages.txt"

## Insert message body:
echo "These packages are currently installed on $HOSTNAME:" > /tmp/installed_packages.txt
echo "----------" >> /tmp/installed_packages.txt

## Debian
folderName="/etc/apt"
if test -d $folderName
then
    ## Create the output file:
    aptitude search '~i !~M' -F %p >> /tmp/installed_packages.txt

fi

## Arch Linux
folderName="/etc/pacman.d"
if test -d $folderName
then
    ## Create the output file:
    pacman -Qe >> /tmp/installed_packages.txt
fi

## Fedora
folderName="/etc/yum"
if test -d $folderName
then
    ## Create the output file:
    rpm -qa | sort >> /tmp/installed_packages.txt
fi


## Email the output file:
/bin/echo $BODY | /usr/bin/mailx -r $SMTPFROM -s "$SUBJECT" -a $ATTACHMENT -S smtp="$SMTPSERVER" -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user="$SMTPUSER" -S smtp-auth-password="$SMTPPASS" -S ssl-verify=ignore $SMTPTO

## Delete the output file, since we're done with it:
sudo rm /tmp/installed_packages.txt
