#!/bin/bash

## Test it the local host is Arch-based:
if [ -d /etc/pacman.d ]
then
	## Run the Arch version of the update command:
	if which yaourt > /dev/null; then
		yaourt -Syu --aur
	else
		sudo pacman -Syu
	fi

fi

## Test if the local host is Debian-based:
if [ -d /etc/apt ]
then
	## Run the Debian version of the update command:
	sudo apt-get update && sudo apt-get dist-upgrade
fi
